# Generated by Django 4.1.4 on 2023-05-17 04:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_type', models.CharField(choices=[('blood', 'Blood'), ('urine', 'Urine'), ('saliva', 'Saliva'), ('stool', 'Stool'), ('tissue', 'Tissue'), ('swabs', 'Swabs'), ('csf', 'Cerebrospinal fluid (CSF)'), ('tumor_markers', 'Tumor markers')], max_length=50)),
                ('collection_date', models.DateField()),
                ('collection_time', models.TimeField()),
                ('is_sent_to_lab', models.BooleanField(default=False)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='appointment_details', to='App_main.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultDocument', models.FileField(upload_to='test_result_documents/')),
                ('result', models.TextField()),
                ('date_processed', models.DateField(auto_now_add=True)),
                ('medical_sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App_main.medicalsample')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('O', 'O')], max_length=1)),
                ('dob', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+880xxxxxxxxxx'.", regex='^\\+?880\\d{10}$')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medicalsample',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='patient_profile', to='App_main.patientprofile'),
        ),
    ]
