# Generated by Django 4.1.4 on 2023-05-17 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0002_servicemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='service_details', to='App_main.servicemodel'),
            preserve_default=False,
        ),
    ]
